name: Use Secret in Script

on:
  push:
    branches:
      - develop

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Usar segredo em um script
        env:
          MY_SECRET: ${{ secrets.TEST_ENV }}
        run: |
          echo "Usando o segredo em um script..."
          # Aqui você pode usar a variável MY_SECRET em um script ou comando
          # Por exemplo, se você estiver rodando um script bash:
          echo "O segredo é acessível na variável MY_SECRET"
