name: Use Secret in Script

on:
  push:
    branches:
      - develop

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Usar segredo em um script
        run: |
          echo "Usando o segredo em um script..."
          # Aqui você pode usar a variável MY_SECRET em um script ou comando
          # Por exemplo, se você estiver rodando um script bash:
          echo "O segredo é acessível na variável ${{ secrets.MY_SECRET }}"
          echo "Obtendo IP público..."
          curl "https://api.ipify.org?format=json"
