name: Print new code

on:
  push:
    branches:
      - develop

jobs:
  print-new-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Verificar número de commits
        id: commit_check
        run: |
          # Verifica se é o primeiro commit
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "first_commit=true" >> $GITHUB_ENV
          else
            echo "first_commit=false" >> $GITHUB_ENV
          fi

      - name: Imprimir código novo/alterado
        run: |
          if [ "$GITHUB_ENV" == "first_commit=true" ]; then
            echo "Primeiro commit detectado. Exibindo todos os arquivos:"
            git ls-files
            git show HEAD
          else
            echo "Arquivos modificados/adicionados:"
            git diff --name-only HEAD~1 HEAD

            echo "Conteúdo dos arquivos modificados/adicionados:"
            git diff HEAD~1 HEAD -- . ':(exclude)*.yml'
          fi
