name: Print new code

on:
  push:
    branches:
      - develop

jobs:
  print-new-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Verificar número de commits
        id: commit_check
        run: |
          git diff main
