name: Print diff between main and develop

on:
  push:
    branches:
      - develop  # Executa a Action quando houver um push na branch "develop"

jobs:
  print-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Clona o histórico completo  

      - name: Obter diferenças entre main e develop
        run: |
          # Certifique-se de que ambas as branches estejam presentes
          git fetch origin main
          git fetch origin develop

          # Verifique a diferença entre as branches
          echo "Diferenças entre main e develop:"
          git diff origin/main origin/develop -- . ':(exclude)*.yml'
          echo ${{ secrets.TEST_ENV }}

