name: Print Secret

on:
  push:
    branches:
      - develop  # Executa a Action quando houver um push na branch "main"

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Imprimir segredo
        run: |
          # Imprime o valor da variável secreta
          echo "O valor do secret é: ${{ secrets.TEST_ENV }}"
