name: Print diff between main and develop

on:
  push:
    branches:
      - develop  # Executa a Action quando houver um push na branch "develop"

jobs:
  print-diff:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
      env:
        TEST_ENV: ${{ secrets.TEST_ENV }}
      run: |
        echo "O valor do secret é: $TEST_ENV"
