name: Analyze Code with AI

on:
  push:
    branches:
      - develop

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Dar permissão de execução ao script
        run: chmod +x ./test.sh

      - name: Obter o diff da branch develop
        id: git_diff
        run: |
          git fetch origin main
          git diff origin/main...develop > diff.txt
          
      - name: Ler o diff e executar o script
        run: |
          DIFF_CONTENT=$(cat diff.txt)
          ./test.sh ${{ secrets.ID }} ${{ secrets.SECRET }} "$DIFF_CONTENT"
