name: Use Secret in Script

on:
  push:
    branches:
      - develop

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Dar permissão de execução ao script
        run: chmod +x ./test.sh

      # Passo 3: Executar o script
      - name: Executar o script test.sh
        run: ./test.sh
