name: Analyze Code with AI

on:
  push:
    branches:
      - develop

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Dar permissão de execução ao script
        run: chmod +x ./test.sh

      - name: Obter o diff da branch develop
        id: git_diff
        run: |
          git fetch origin main
          git diff origin/main develop > diff.txt  # Gera o diff entre 'main' e 'develop'
          
      - name: Exibir o conteúdo do diff.txt
        run: |
          echo "Conteúdo de diff.txt:"
          cat diff.txt

      - name: Adicionar contexto de análise ao diff e executar o script
        run: |
          DIFF_CONTENT=$(cat diff.txt)
          ANALYSIS_CONTEXT="Você é um experiente engenheiro de software sênior. Fará o code review do seguinte código, que é um diff entre duas branches. Observe detalhes de clean code, segurança e boas práticas de programação."
          FULL_CONTENT="$ANALYSIS_CONTEXT\n\n$DIFF_CONTENT"
          echo "Conteúdo combinado para análise:"
          echo "$FULL_CONTENT"  # Exibe o conteúdo combinado (contexto + diff)
          ./test.sh ${{ secrets.ID }} ${{ secrets.SECRET }} "boa tarde"
